/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@ionic/core';
import 'ionicons';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppHome {
    'history': RouterHistory;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface AppProfile {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface BlogIndex {
    'getPosts': () => Promise<{ file: string; title: string; date: string; unique_link: string; }[]>;
    'history': RouterHistory;
    'routerHistory': RouterHistory;
  }
  interface BlogIndexAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'routerHistory'?: RouterHistory;
  }

  interface BlogPostWrapper {
    'metadata': any;
    'uniqueLink': string;
  }
  interface BlogPostWrapperAttributes extends StencilHTMLAttributes {
    'metadata'?: any;
    'uniqueLink'?: string;
  }

  interface BlogPost {
    'history': RouterHistory;
    'match': MatchResults;
    'metadata': string;
    'uniqueLink': string;
  }
  interface BlogPostAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'metadata'?: string;
    'uniqueLink'?: string;
  }

  interface Blog {}
  interface BlogAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'BlogIndex': Components.BlogIndex;
    'BlogPostWrapper': Components.BlogPostWrapper;
    'BlogPost': Components.BlogPost;
    'Blog': Components.Blog;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'blog-index': Components.BlogIndexAttributes;
    'blog-post-wrapper': Components.BlogPostWrapperAttributes;
    'blog-post': Components.BlogPostAttributes;
    'blog': Components.BlogAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLBlogIndexElement extends Components.BlogIndex, HTMLStencilElement {}
  var HTMLBlogIndexElement: {
    prototype: HTMLBlogIndexElement;
    new (): HTMLBlogIndexElement;
  };

  interface HTMLBlogPostWrapperElement extends Components.BlogPostWrapper, HTMLStencilElement {}
  var HTMLBlogPostWrapperElement: {
    prototype: HTMLBlogPostWrapperElement;
    new (): HTMLBlogPostWrapperElement;
  };

  interface HTMLBlogPostElement extends Components.BlogPost, HTMLStencilElement {}
  var HTMLBlogPostElement: {
    prototype: HTMLBlogPostElement;
    new (): HTMLBlogPostElement;
  };

  interface HTMLBlogElement extends Components.Blog, HTMLStencilElement {}
  var HTMLBlogElement: {
    prototype: HTMLBlogElement;
    new (): HTMLBlogElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'blog-index': HTMLBlogIndexElement
    'blog-post-wrapper': HTMLBlogPostWrapperElement
    'blog-post': HTMLBlogPostElement
    'blog': HTMLBlogElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'blog-index': HTMLBlogIndexElement;
    'blog-post-wrapper': HTMLBlogPostWrapperElement;
    'blog-post': HTMLBlogPostElement;
    'blog': HTMLBlogElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
