/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface BlogIndex {
    'getPosts': () => void;
  }
  interface BlogIndexAttributes extends StencilHTMLAttributes {}

  interface BlogPost {
    'post': string;
  }
  interface BlogPostAttributes extends StencilHTMLAttributes {
    'post'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'BlogIndex': Components.BlogIndex;
    'BlogPost': Components.BlogPost;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'blog-index': Components.BlogIndexAttributes;
    'blog-post': Components.BlogPostAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLBlogIndexElement extends Components.BlogIndex, HTMLStencilElement {}
  var HTMLBlogIndexElement: {
    prototype: HTMLBlogIndexElement;
    new (): HTMLBlogIndexElement;
  };

  interface HTMLBlogPostElement extends Components.BlogPost, HTMLStencilElement {}
  var HTMLBlogPostElement: {
    prototype: HTMLBlogPostElement;
    new (): HTMLBlogPostElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'blog-index': HTMLBlogIndexElement
    'blog-post': HTMLBlogPostElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'blog-index': HTMLBlogIndexElement;
    'blog-post': HTMLBlogPostElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
